# Generated by Django 3.0.3 on 2020-09-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('ssn', models.CharField(max_length=11)),
                ('drug_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('resident', models.BooleanField()),
                ('veteran', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('yearly_income', models.IntegerField(max_length=20)),
                ('household_income', models.IntegerField(max_length=20)),
                ('health_conditions', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='care_connect_app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_coverage', models.BooleanField()),
                ('coverage_type', models.CharField(max_length=100)),
                ('coverage_other', models.CharField(max_length=255)),
                ('primary_name', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=100)),
                ('primary_id', models.CharField(blank=True, max_length=100)),
                ('primary_group', models.CharField(blank=True, max_length=100)),
                ('primary_bin', models.CharField(blank=True, max_length=100)),
                ('secondary_name', models.CharField(blank=True, max_length=100)),
                ('secondary_phone', models.CharField(blank=True, max_length=100)),
                ('secondary_id', models.CharField(blank=True, max_length=100)),
                ('secondary_group', models.CharField(blank=True, max_length=100)),
                ('secondary_bin', models.CharField(blank=True, max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('relation_other', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_coverage', to='care_connect_app.Patient')),
            ],
        ),
    ]
