# Generated by Django 3.1 on 2020-09-30 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('ssn', models.CharField(max_length=11)),
                ('status', models.CharField(default='New', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='ProgForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('singinc', models.IntegerField()),
                ('coupinc', models.IntegerField()),
                ('otherinc', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.address')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.diseases')),
                ('form', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.progforms')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('resident', models.BooleanField()),
                ('veteran', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('yearly_income', models.IntegerField()),
                ('household_income', models.IntegerField()),
                ('health_conditions', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.diseases')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='care_connect_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=14)),
                ('website', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_coverage', models.BooleanField()),
                ('coverage_type', models.CharField(max_length=100)),
                ('coverage_other', models.CharField(max_length=255)),
                ('primary_name', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=100)),
                ('primary_id', models.CharField(blank=True, max_length=100)),
                ('primary_group', models.CharField(blank=True, max_length=100)),
                ('primary_bin', models.CharField(blank=True, max_length=100)),
                ('secondary_name', models.CharField(blank=True, max_length=100)),
                ('secondary_phone', models.CharField(blank=True, max_length=100)),
                ('secondary_id', models.CharField(blank=True, max_length=100)),
                ('secondary_group', models.CharField(blank=True, max_length=100)),
                ('secondary_bin', models.CharField(blank=True, max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('relation_other', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_coverage', to='care_connect_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Generics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.diseases')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.drug')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.manufacturers')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.manufacturers'),
        ),
    ]
