# Generated by Django 3.1 on 2020-10-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='insurance',
            new_name='patient',
        ),
    ]
