# Generated by Django 3.1 on 2020-09-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progforms',
            name='patientsignature',
        ),
        migrations.RemoveField(
            model_name='progforms',
            name='providersignature',
        ),
        migrations.AddField(
            model_name='progforms',
            name='name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
