# Generated by Django 3.0.3 on 2020-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='household_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='yearly_income',
            field=models.IntegerField(),
        ),
    ]
