# Generated by Django 3.1 on 2020-09-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_connect_app', '0002_auto_20200922_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('ssn', models.CharField(max_length=11)),
                ('status', models.CharField(default='Active', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_connect_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('resident', models.BooleanField()),
                ('veteran', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('yearly_income', models.IntegerField()),
                ('household_income', models.IntegerField()),
                ('health_conditions', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diseases', models.ManyToManyField(to='care_connect_app.Diseases')),
                ('drug', models.ManyToManyField(to='care_connect_app.Drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='care_connect_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_coverage', models.BooleanField()),
                ('coverage_type', models.CharField(max_length=100)),
                ('coverage_other', models.CharField(max_length=255)),
                ('primary_name', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=100)),
                ('primary_id', models.CharField(blank=True, max_length=100)),
                ('primary_group', models.CharField(blank=True, max_length=100)),
                ('primary_bin', models.CharField(blank=True, max_length=100)),
                ('secondary_name', models.CharField(blank=True, max_length=100)),
                ('secondary_phone', models.CharField(blank=True, max_length=100)),
                ('secondary_id', models.CharField(blank=True, max_length=100)),
                ('secondary_group', models.CharField(blank=True, max_length=100)),
                ('secondary_bin', models.CharField(blank=True, max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('relation_other', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_coverage', to='care_connect_app.patient')),
            ],
        ),
    ]
