# Generated by Django 3.1 on 2020-10-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_connect_app', '0002_auto_20201001_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='relation_other',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='secondary_bin',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='secondary_group',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='secondary_id',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='secondary_name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='secondary_phone',
        ),
    ]
